# Generated by Django 3.1.2 on 2020-11-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentable_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
